### ISSUE TITLE
Use cs-common nullability testing for MpSpdzIntegrationUtils

### ISSUE THREAD

**Issue by grevend-bosch** [carbynestack/mp-spdz-integration#11]
Test the class constructor using `@NullableParamSource`.

**Comment by zlemon819** [comment]
> Test the class constructor using `@NullableParamSource`.

hi, i wonder how you test the project. Now i test it in IDEA, but could not figure out what is the "common-testing" in pom.xml?  Thank you.

**Comment by sbckr** [comment]
> > Test the class constructor using `@NullableParamSource`.
> 
> hi, i wonder how you test the project. Now i test it in IDEA, but could not figure out what is the "common-testing" in pom.xml? Thank you.

@zlemon819 Thank you for your question.
The issue is addressed by carbynestack/mp-spdz-integration#16
